#!/usr/bin/env sh

swaylock \
        --screenshots \
        --clock \
        --datestr "%a, %d/%m/%y" \
        --indicator \
        --indicator-radius 100 \
        --indicator-thickness 7 \
        --effect-blur 7x5 \
        --effect-vignette 0.5:0.5 \
        --ring-color bb00cc \
        --key-hl-color 50fa7b \
        --line-color 00000000 \
        --inside-color 282a36 \
        --separator-color 50fa7b \
        --ring-color 00000000 \
        --text-color f8f8f8ff \
        --text-ver-color f8f8f8ff \
        --text-wrong-color f8f8ff \
        --inside-ver-color 282a36 \
        --inside-wrong-color 282a36 \
        --ring-ver-color 00000000 \
        --ring-wrong-color 00000000 \
        --line-ver-color 00000000 \
        --line-wrong-color 00000000
