# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "snd-hda-intel.model=auto" "snd-intel-dspcfg.dsp_driver=1" ]; # "snd-hda-intel.index=0"];
  boot.blacklistedKernelModules =  [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b5b66f85-00bb-4c01-a940-ab85283c3417";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0aaf760b-6d5e-41dc-84fc-a47be702088f".device = "/dev/disk/by-uuid/0aaf760b-6d5e-41dc-84fc-a47be702088f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E5F8-A023";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0847e7cb-8a94-465f-9fe1-94db893a2fff"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
