#!/usr/bin/env bash
sxhkd &
dunst &
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/pic/Wallpaper/sakuraflower.png
xset -dpms s off
nextcloud --background &

export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config click_to_focus      button1
bspc config border_width        3
bspc config window_gap          6
bspc config swallow_first_click false
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_focus   false

bspc rule -a mpv state=pseudo_tiled
bspc rule -a Komikku state=pseudo_tiled
bspc rule -a Sxiv state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a scrcpy state=floating
bspc rule -a pomotroid state=pseudo_tiled
bspc rule -a Emacs state=tiled

bspc config normal_border_color "#9ca0b0"
bspc config active_border_color "#9ca0b0"
bspc config focused_border_color "#ea76cb"
bspc config presel_feedback_color "#acb0be"

