# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-25976d52-a40a-48cc-9f26-fefe979b9f79";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-25976d52-a40a-48cc-9f26-fefe979b9f79".device = "/dev/disk/by-uuid/25976d52-a40a-48cc-9f26-fefe979b9f79";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/2D88-E975";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/mapper/luks-754fdd9f-2361-419d-92c9-57d04ce22aec"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = [ pkgs.sof-firmware ];
}
